// Firebase configuration for Shadow Sentinel
// Generated by FlutterFire CLI — project: shadow-sentinel-app

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name} — run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZajGee9P8DWAKQhHj8B1UyNvRxs2l5d4',
    appId: '1:1024912967279:web:54aa11bdd08a5efff4af9a',
    messagingSenderId: '1024912967279',
    projectId: 'shadow-sentinel-df66d',
    authDomain: 'shadow-sentinel-df66d.firebaseapp.com',
    storageBucket: 'shadow-sentinel-df66d.firebasestorage.app',
  );
}
