// Firebase configuration for Shadow Sentinel
// Generated by FlutterFire CLI — project: shadow-sentinel-app

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name} — run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'PASTE_YOUR_FIREBASE_API_KEY',
    appId: 'PASTE_YOUR_FIREBASE_APP_ID',
    messagingSenderId: 'PASTE_YOUR_MESSAGING_SENDER_ID',
    projectId: 'PASTE_YOUR_PROJECT_ID',
    authDomain: 'PASTE_YOUR_AUTH_DOMAIN',
    storageBucket: 'PASTE_YOUR_STORAGE_BUCKET',
  );
}
