// Firebase configuration for Shadow Sentinel
// Generated by FlutterFire CLI — project: shadow-sentinel-app

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name} — run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVjEe8-HT2_2NUPpIYFmYyTD5o9xOlv20',
    appId: '1:1054561929122:web:259aa6fd2a04e522a4d4fb',
    messagingSenderId: '1054561929122',
    projectId: 'shadow-sentinel-app',
    authDomain: 'shadow-sentinel-app.firebaseapp.com',
    storageBucket: 'shadow-sentinel-app.firebasestorage.app',
  );
}
